name: FlightPlease
version: ${project.version}
main: me.abstention.flightplease.FlightPlease
api-version: 1.16
authors: [ Abstention ]
description: Allows for flight!
commands:
  fly:
    description: Toggle Flight!
    aliases: [togglefly]
